// flow-typed signature: bba48e11740a809d1b66ee4bfc3e51b7
// flow-typed version: <<STUB>>/check-dependencies_v1.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-dependencies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-dependencies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-dependencies/bin/cli' {
  declare module.exports: any;
}

declare module 'check-dependencies/lib/check-dependencies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-dependencies/bin/cli.js' {
  declare module.exports: $Exports<'check-dependencies/bin/cli'>;
}
declare module 'check-dependencies/lib/check-dependencies.js' {
  declare module.exports: $Exports<'check-dependencies/lib/check-dependencies'>;
}
