// flow-typed signature: 06917fd03c7e5ef130981e8b3fc4dc7c
// flow-typed version: <<STUB>>/clf-date_v0.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clf-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clf-date' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clf-date/bin/clf-date' {
  declare module.exports: any;
}

declare module 'clf-date/out/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clf-date/bin/clf-date.js' {
  declare module.exports: $Exports<'clf-date/bin/clf-date'>;
}
declare module 'clf-date/out/main.js' {
  declare module.exports: $Exports<'clf-date/out/main'>;
}
