// flow-typed signature: e20cd1292958971e5416638161ac6083
// flow-typed version: <<STUB>>/express-static-gzip_v0.3.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-static-gzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-static-gzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-static-gzip/index' {
  declare module.exports: $Exports<'express-static-gzip'>;
}
declare module 'express-static-gzip/index.js' {
  declare module.exports: $Exports<'express-static-gzip'>;
}
