// flow-typed signature: 8426ab3a7a1934362ec7918b8025980b
// flow-typed version: <<STUB>>/react-nested-status_v0.2.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-nested-status'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-nested-status' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-nested-status/test/common' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-nested-status/index' {
  declare module.exports: $Exports<'react-nested-status'>;
}
declare module 'react-nested-status/index.js' {
  declare module.exports: $Exports<'react-nested-status'>;
}
declare module 'react-nested-status/test/common.js' {
  declare module.exports: $Exports<'react-nested-status/test/common'>;
}
